SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS PCX_ORGNIZATION;




/* Create Tables */

-- 机构表
CREATE TABLE PCX_ORGNIZATION
(
	ORG VARCHAR(12) NOT NULL COMMENT '机构号',
	ORG_NAME VARCHAR(40) COMMENT '机构名称',
	ORG_DESC VARCHAR(500) COMMENT '机构描述',
	JPA_VERSION INT COMMENT 'JPA_VERSION',
	PRIMARY KEY (ORG)
) COMMENT = '机构表';



